services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: clinic-system-app
        container_name: clinic_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - clinic-network

    web:
        image: nginx:alpine
        container_name: clinic_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - clinic-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: clinic_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-clinic_system}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-clinic_user}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - clinic-network

    redis:
        image: redis:alpine
        container_name: clinic_redis
        restart: unless-stopped
        networks:
            - clinic-network

networks:
    clinic-network:
        driver: bridge

volumes:
    dbdata:
